### ISSUE TITLE
Guild of Theives (1987)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2448]
BaneMind discovered that the game is spelt incorrectly in manual, bat, LB etc. Should be Guild of Thieves (1987)

**Comment by exoscoriae** [comment]
fixed

**Comment by Python-Exoproject** [comment]
The original files (zip, bat, manual, etc) are still present

**Comment by exoscoriae** [comment]
not in my copy?

**Comment by exoscoriae** [comment]
confirmed. no copies in my version

**Comment by Python-Exoproject** [comment]
Must be sync issue again
