### ISSUE TITLE
John Madden Football II (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3411]
Another DAC game that is garbled at the moment. To fix, switch to using dosbox X.

This will need conf changed to "fullresolution=desktop". For the MT32 option to work, grab exception.bat from "Golden Eagle (1991)" which is another X game with MT32.

Only remaining issue is that the mouse cursor doesnt track to the game mouse cursor properly when in X

**Comment by exoscoriae** [comment]
fixed

@Python-Exoproject to fix the mouse issue, you add
autolock=true
autolock_feedback=none
to the SDL section of the conf file

**Comment by Python-Exoproject** [comment]
I have a double cursor issue still. Maybe we need autolock=true as well?
