### ISSUE TITLE
Air Troubles (1995)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3998]
**Air Troubles (1995)** contains a couple of default pilots (wil and guido) that can be removed for a "cleaner" version.

**Comment by exoscoriae** [comment]
done

**Comment by Python-Exoproject** [comment]
My zip has the right date (7/7/22), but the pilots are still present?

**Comment by exoscoriae** [comment]
if you delete them, and restart the game, they are back....

I deleted the players.dat file, and now they are gone
